eureka:
  administrator:
    name: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
security:
  oauth2:
    client:
      access-token-uri: ${AUTHORIZATION_SERVER_URI}/oauth/token
      user-authorization-uri: ${AUTHORIZATION_SERVER_URI}/oauth/authorize
    resource:
      prefer-token-info: false
      user-info-uri: ${AUTHORIZATION_SERVER_URI}/user