#####################################################################
###                                                               ###
###         A lot of stuff is commented out in this file.         ###
### This is what you would configure in a productive environment. ###
###                                                               ###
#####################################################################
#eureka:
#  administrator:
#    name: ${EUREKA_ADMIN_USERNAME}
#    password: ${EUREKA_ADMIN_PASSWORD}
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_DEFAULT_ZONE}
security:
  oauth2:
#    client:
#      access-token-uri: ${OAUTH2_SERVER_URL}/oauth/token
#      user-authorization-uri: ${OAUTH2_SERVER_URL}/oauth/authorize
    resource:
      prefer-token-info: false
#      user-info-uri: ${OAUTH2_SERVER_URL}/user