authorization-server:
  security:
    max-login-attempts: 3
spring:
  jpa:
    show-sql: true
  mail:
    test-connection: false
server:
  address: localhost
  port: 88
  servlet:
    context-path: /auth