authorization-server:
  security:
    max-login-attempts: ${MAX_LOGIN_ATTEMPTS}
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: authorization-server
  data:
    web:
      pageable:
        default-page-size: 10
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: ${PSQL_DATASOURCE_JDBC_URL}
    username: ${PSQL_DATASOURCE_USERNAME}
    password: ${PSQL_DATASOURCE_PASSWORD}
  flyway:
    url: ${spring.datasource.jdbc-url}
    user: ${PSQL_FLYWAY_USERNAME:${spring.datasource.username}}
    password: ${PSQL_FLYWAY_PASSWORD:${spring.datasource.password}}
  jackson:
    date-format: dd.MM.yyyy HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        auth: true
        imap:
          ssl:
            enable: true
        smtp:
          starttls:
            enable: true
    test-connection: trueF
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
server:
  address: ${OAUTH2_SERVER_URL}
  port: ${SERVER_PORT}