language: java
dist: trusty
jdk:
  - oraclejdk8

sudo: false
install: true

notifications:
  email: false

branches:
  only:
  - master
  - development

addons:
  chrome: stable
  sonarcloud:
    organization: "tbmelabs-github"
    token:
      secure: "m6YtJXyy+gZR1HBrK+kMI8yueXztQ3l0A4aaIO3p+VUviVIsPzYVCuTkZvXdOUpI/w54QKI5wuLdCBeHtfcUWCWrAEfT2DNkz68ENZakiS4Mu4LesQe/d2aWKpzIqPkibp68flnccY9whgX/uYayHha93nuN1j9XmjSKRInj+NSZhzVwZb3DNH6eq1YF+Pz0yVQHvOUoE1Dd8KF1kYBPUMzxVQSpOi0CiwLydBNUK3b4QT4wf5wMLYjELU3Ljl8YqbN4sTMCiR4FGstnOS3fmwe1rCjcmqfof6XO5ro2n+1JKQLdHVMbH6aEFnr21nAsebArDeVSDwGTsaSFg8Vt14HeSW8evWpG+XEINQT9wO9klRXe4cIvN4rUNUNeWVA9h+tjzfVwANVu/byW6qejrqKyiP4tHpepD9gsVTAUiAL0QqH+qudxWLzNBz5uDksdMmexhX/usAxeS51kZDC9xIX1XmzhJiQnPW3gdWkw3guBVYUj9Vby5z1Xz80rimUIr+dGuTqa/2cwjjtkZUpuJdpc6OrTmvmMNIVkWNuyjvifSuVZYZcd6DiRj1cwBtBuo1v07rF0rP5s+TduGze8IMMv08fh1qX6n6oTsFyob8HkVC2T0W9bDVUy08dbK0M+VC47le5HQd+CvZTPW4es45uddRa+6NUBRNvze171RP4="

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE authorization_server_integration;" -U postgres
  - psql -c "CREATE USER authorization_server_integration_user WITH PASSWORD 'authorization_server_integration_user_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE authorization_server_integration TO authorization_server_integration_user;" -U postgres

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pprod

cache:
  directories:
    - "$HOME/.cache"
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
