version: '2'
services:
  elasticsearch_logging:
    image: elasticsearch
    expose:
    - 9200
  logstash_logging:
    image: logstash
    command: logstash -e 'input{ tcp { port => 5000 } } output{ elasticsearch { hosts => ["elasticsearch"] } }'
    ports:
    - 5000:5000
    links:
    - elasticsearch_logging:elasticsearch
    depends_on:
    - elasticsearch_logging
  kibana_logging:
    image: kibana
    ports:
    - 5601:5601
    links:
    - elasticsearch_logging:elasticsearch