version: '3'
services:
  oauth_tokenstore:
    image: redis
  oauth_datasource:
    image: postgres
    environment:
      - POSTGRES_DB=auth_server_database
      - POSTGRES_PASSWORD=af2EszT2
      - POSTGRES_USER=oauth_admin
    volumes:
      - ../authorization-server/src/main/resources/db/installation/auth_database.sql:/docker-entrypoint-initdb.d/init.sql
  eureka-server:
    image: eureka-service-discovery
    environment:
      - EUREKA_DEFAULT_ZONE=http://localhost:8761/eureka
  authorization-server:
    image: authorization-server
    depends_on:
      - oauth_tokenstore
      - oauth_datasource
      - eureka-server
    environment:
      - SERVER_PORT=88
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka
      - MAX_LOGIN_ATTEMPTS=3
      - PSQL_DATABASE_JDBC_URL=jdbc:postgresql://oauth_datasource:5432/auth_server_database
      - PSQL_DATABASE_NAME=auth_server_database
      - PSQL_USERNAME=auth_database_user
      - PSQL_PASSWORD=auth_database_user_password
      - REDIS_HOST=oauth_tokenstore
      - REDIS_PORT=6379
  login-service:
    image: login-service
    depends_on:
      - oauth_tokenstore
      - authorization-server
      - eureka-server
    environment:
      - SERVER_PORT=88
      - APPLICATION_NAME=login
      - CLIENT_ID=login
      - CLIENT_SECRET=C0F6463B-B1E7-4AFE-A63D-BE90C9187E82
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka
      - OAUTH2_SERVER_BASE_URI=http://authorization-server:88
  zuul-server:
    image: zuul-entry-server
    depends_on:
      - oauth_tokenstore
      - authorization-server
      - eureka-server
    environment:
      - CLIENT_ID=zuul
      - CLIENT_SECRET=
      - EUREKA_DEFAULT_ZONE=http://eureka-server:8761/eureka
      - OAUTH2_SERVER_BASE_URI=http://authorization-server:88
      - REDIS_HOST=oauth_tokenstore
      - REDIS_PORT=6379
    ports:
      - "80:80"