elasticsearch_logging:
  image: elasticsearch
logstash_logging:
  image: logstash
  command: bash -c "plugin install /etc/logstash/conf.d/logstash-input-log4j2-5.2-java.gem && logstash -f /etc/logstash/conf.d/logstash.conf"
  volumes:
    - ./logstash-log4j2/config:/etc/logstash/conf.d
    - ./logstash-log4j2/local_gems:/opt/logstash/vendor/local_gems #/5acd7b33/logstash-input-log4j2-5.2-java/vendor/log4j-api-2.1
  ports:
    - "5000:5000"
  links:
    - elasticsearch_logging
kibana_logging:
  image: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch_logging